[Distribution]
Distribution=debian
Release=trixie
Mirror=http://deb.debian.org/debian

[Content]
Packages=
    # base system
    dbus-broker
    systemd-sysv
    # login and similar necessities
    libnss-myhostname
