[Distribution]
Distribution=debian
Release=trixie
Mirror=http://deb.debian.org/debian

[Output]
Format=uki
ManifestFormat=json

[Content]
# Set a root password to allow logging in via the console in case something goes
# wrong during the initrd or install phase.
#RootPassword=

Bootloader=none
WithRecommends=no
Packages=
    # base system
    ?priority(required)
    dbus-broker
    systemd-sysv
    systemd-boot-efi
    # login and similar necessities
    libnss-myhostname
    libnss-systemd
    libpam-systemd
    # tooling
    ca-certificates
    curl
    dmidecode
    ethtool
    iproute2
    jq
    less
    man
    mtr
    net-tools
    openssh-server
    procps
    vim

# Configure OS to skip any setup prompts.
Hostname=localhost
Keymap=us
Locale=C.UTF-8
Timezone=UTC

# Drop unnecessary files to reduce image size.
RemoveFiles=
    /usr/share/doc/*
    /usr/share/info/*
    /usr/share/locale/*
    /var/cache/apt/*
    /var/lib/apt/lists/*
    /var/log/journal/*
