[Match]
Distribution=ubuntu

[Content]
Packages=
    linux-image-generic
    # linux-firmware depends on all firmware packages which are several hundred
    # megabytes. However, it is also a virtual package which can be provided by
    # linux-firmware-minimal. We install the minimal variant to keep the image
    # size small, a large image may fail to boot because of the excessive memory
    # that has to be allocated early on.
    linux-firmware-minimal
