#!/bin/sh

set -eu

if [ $# -ne 1 ]; then
    echo "usage: $0 <metal|virt|factorio>" >&2
    exit 1
fi

repo="ghcr.io/maxmoehl/debian"
target="$1"
date=$(date +%Y%m%d)

case "$target" in
    metal)
        profiles="metal,disk-install,ironcore"
        archs="x86-64 arm64"
        tag="trixie-metal"
        layer="uki"
        ext="efi"
        ;;
    virt)
        profiles="virt,default-user"
        archs="x86-64 arm64"
        tag="trixie-virt"
        layer="rootfs"
        ext="raw"
        ;;
    factorio)
        profiles="virt,default-user,factorio"
        archs="x86-64"
        tag="factorio"
        layer="rootfs"
        ext="raw"
        ;;
    *)
        echo "error: unknown target '$target', must be 'metal', 'virt', or 'factorio'" >&2
        exit 1
        ;;
esac

filename=$(echo "$profiles" | tr ',' '_')

set -x

rm -f mkosi.output/*
for arch in $archs; do
    mkosi --architecture "$arch" --profile "$profiles" build
done

configs=""
for arch in $archs; do
    case "$arch" in
        x86-64) oci_arch="amd64" ;;
        arm64)  oci_arch="arm64" ;;
    esac
    configs="$configs --config arch=${oci_arch},${layer}=mkosi.output/${filename}_${arch}.${ext}"
done

ironcore-image build \
    --tag "${repo}:${tag}-${date}" \
    $configs

ironcore-image push \
    --push-sub-manifests \
    "${repo}:${tag}-${date}"

oras tag "${repo}:${tag}-${date}" "$tag"
