[Distribution]
Distribution=debian
Release=trixie
Mirror=http://deb.debian.org/debian

[Output]
Format=uki
ImageId=ironcore-debian
ManifestFormat=json

[Content]
# Set a root password to allow logging in via the console in case something goes
# wrong during the initrd or install phase.
#RootPassword=

Packages=
    # base system
    ?priority(required)
    dbus-broker
    linux-image-amd64
    systemd-sysv
    # login and similar necessities
    libnss-myhostname
    libnss-systemd
    libpam-systemd
    # disk install dependencies
    dosfstools
    e2fsprogs
    efibootmgr
    systemd-boot
    systemd-boot-efi
    systemd-repart
    # tooling
    ca-certificates
    curl
    dmidecode
    ethtool
    frr
    iproute2
    jq
    less
    man
    mtr
    net-tools
    nftables
    openssh-server
    procps
    sudo
    vim
WithRecommends=no

# Make the image usable as an initramfs to allow us to hack around early in the
# boot process. This is used to setup the overlay to prevent writes to the
# rootfs as well as hooking any scripts before the system pivots and boots into
# the live system, e.g. for installing to disk.
MakeInitrd=yes
KernelCommandLine=ic.ovl console=tty0

# Configure OS to skip any setup prompts.
Locale=C.UTF-8
Hostname=localhost
Timezone=UTC
Keymap=us

# Drop unnecessary files to reduce image size.
RemoveFiles=
    /usr/share/doc/*
    /usr/share/info/*
    /usr/share/locale/*
    /var/cache/apt/*
    /var/lib/apt/lists/*
    /var/log/journal/*
