[Distribution]
Distribution=ubuntu
Release=noble
Repositories=universe

[Content]
Packages=
    apt # don't even ask...
    dbus
    sudo
    passwd
    uidmap
    systemd

# Forces Ignition to run its initialization routines on first boot
KernelCommandLine=ignition.firstboot=1    
