[Output]
Format=disk

[Content]
Hostname=rescue
KernelCommandLine=ro systemd.volatile=state
Bootloader=systemd-boot
Bootable=yes
Packages=
    bridge-utils
    cryptsetup
    dosfstools
    gdisk
    iputils-ping
    lshw
    lvm2
    mdadm
    nmap
    nvme-cli
    parted
    pciutils
    rsync
    smartmontools
    strace
    sudo
    sysstat
    tcpdump
    usbutils
    xfsprogs

RemoveFiles=
